version: '3.3'

services:

  db:
    env_file:
      - .env
    image: postgres:13.0-alpine
    ports:
       - '5432'

    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    restart: always

  backend:
    image: admin12352354/foodgram
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/backend/static/
      - media_value:/backend/media/
      - ../frontend/build:/usr/share/nginx/html
      - ../docs:/usr/share/nginx/html/api/docs
      - ../docs:/usr/share/nginx/html/api/docs/openapi-schema.yml
    restart: always
    depends_on:
      - frontend

  frontend:
    image: admin12352354/foodgram-frontend
    volumes:
      - result_build:/app/result_build/build/
    depends_on:
      - backend



volumes:
  result_build:
  postgres_data:
  static_value:
  media_value: